name: Build Immich ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg libvips-dev jq uuid-runtime python3 python3-pip pipx
          pipx install uv
          sudo ln -s ~/.local/bin/uv /usr/local/bin/uv
          npm install -g pnpm node-gyp

      - name: Build Immich
        run: |
          export npm_config_platform=linux
          export npm_config_arch=arm64
          export npm_config_libc=glibc
          export NODE_OPTIONS=--max-old-space-size=4096
          bash install.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immich-arm64
          path: ~/immich/
          retention-days: 1
